# Generated by Django 2.2.6 on 2019-10-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
