# Generated by Django 2.2.6 on 2019-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapi', '0002_auto_20191009_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
