# Generated by Django 2.2.6 on 2019-10-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapi', '0003_auto_20191009_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
