# Generated by Django 2.2.6 on 2019-10-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapi', '0005_auto_20191009_1344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
    ]
