# Generated by Django 2.2.6 on 2019-10-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickapi', '0006_auto_20191009_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('nit', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=60)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickapi.Client')),
            ],
        ),
    ]
