# Generated by Django 2.2.6 on 2019-10-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapi', '0007_bills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bills',
            new_name='Bill',
        ),
    ]
