# Generated by Django 2.2.6 on 2019-10-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickapi', '0008_auto_20191009_1351'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bill',
            table='bills',
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
    ]
