# Generated by Django 2.2.6 on 2019-10-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapi', '0009_auto_20191009_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
