# Generated by Django 2.2.6 on 2019-10-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickapi', '0010_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickapi.Bill')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickapi.Product')),
            ],
            options={
                'db_table': 'bills_products',
            },
        ),
    ]
